model_function: Conversation
eos_token_id: 50256
bos_token_id: 50256
fmt_string: |
  {{ for dialogue_line in history }}
  {dialogue_line.character.name}: {dialogue_line.line}
  {{ endfor }}
temperature: 0.9
top_k: 5
max_generated_length: 25